name: lojong_test_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  flutter_html: ^3.0.0-beta.2 

  # Network
  dio: ^5.4.0
  chucker_flutter: ^1.6.2
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_file_store: ^1.2.3

  # Utils
  get_it: ^7.6.6
  path_provider: ^2.1.2

  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1 
  mocktail: ^1.0.2
  network_image_mock: ^2.0.1

flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/
